services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        BUNDLE_WITHOUT: ""
    volumes:
      - ..:/workspace:cached
    command: sh -lc 'cd /workspace && bundle exec rails s -b 0.0.0.0 -p 3000'
    depends_on:
      - postgres
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/forms_runner_development
      REDIS_URL: redis://redis:6379/0
      SETTINGS__GOVUK_ONE_LOGIN__PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRFlDc1JvY3ZEQm1qSE8KamVWemkwV3p2UGNKVExEcHNDdkRyU2U4bWdXZlgyNzFhQlZRUU84bmZOaStGOFVUaUM2NGg1NjM3NTF5WnVFaApTck9DWm9oMC9taGxZZVJ1ZlZnQTVRc3pLVkIweXNGckl6VVJkbkM5SXBQem9Cb0M3dWRrNGlNOTVjR2RqMW4xCjM0a2Q5ZlhJRjV0WjZ6aGMxNlpaTG1FQStScEZyOWc2YzJyTUlJUG9RclBNMWhOcU53eHdLQ0Yvd3VUTnFwQWQKbkhKZWFqV3h3L2xDNkw1L1FqOWMzRmJFNi9UUDRvbWE2SDU1Y0tIMW9ZcVdPMGEyaE5wM21yYi9kVXVySWVEZQpkcFRHdkxocW9NQnZidmFYcTJ1MFc4a2lqYkR0aXNXTWJ3bUlZVVUzYldKcURwak1Ib2RIelFVaGNaZjAvdExuCmh1UzFWNDZWQWdNQkFBRUNnZ0VCQUlKbkRXS1dibWdOc0o2aTI2ckFtQlFEcllFNWYxZXU5TnVwdXVDR2YzcFIKV21KYXJ2TEFIeHJRcXVzaTRkd0dTVjBzejBycklUZ2FqUzFSTDhVNEtvbWp2bFBqb01Sb2VDUWlISDZISTM4NwptMEFXQWtSR0g0cXFRbSs5WmJYN2lrUkVrMDBiVDZEUkZGWHExWkwyRWFMelROd2J0T3VsWjAxUlIxQVZEQnlmCkNTN29MSG1ZaklyYjl2WDVjblN4UDlHWWxIbXJyTVlzc283dk9LQUx4UFYwRDVUaDhxNklidkJwMW5ScjY4eVYKczI3TEI2WXBJTzk5Nk5tMUtBS0tJT01xb0RuTjRSNlRyblhJQ08ySWJSakhDT2RtbStMZVYwaG4yaHVrQ28vcQpnbVZJOWJFemtWMWZLVk50VmpzMExPU1NXZkc4YVZ2Szh0dTJQQnZZOEVrQ2dZRUErQ0w2T2tKaklraW12K2cxClJsOStMbzV1amJiT0g4M0Y4d0hxRTRReXRScnJOZUNzVVVRSkMrclM2UGZSeGhRUnc3V3dzNFFtbklsR0RzcEMKaDQ4OE5OczlTOXlaa0plQ1AvNENpQWVOM3ZhMGN3YS9yVzZjNmorZmgxYkl2aUtNaE9WcC9EeWhCY25IV1NIRQpkby9lQzZnSHVoSHAySTBrSmkreTN1Uzl2d01DZ1lFQTN1TnJ0UHhIWkZISGp4U05zYnN3Ymxpa2pxOE9ZWUh2CldnYml4RzhaQ25hY3JNNFVrS1BzM2M4WGxUeWtqaEdVUnZrUnpWdWNrOTdCVjhxd3RTblZLUGxkR1U2L1Z6c3kKdUJtYlF6YTk2dUVZdVpJb1JOQ2RrNnpJeFFQK0t3NTRuU1VDNGxaRDl4aTlMSUpzNDFEYXcxbDRGYkl1MG5HTAo2WVVtTXZqMm5JY0NnWUVBeHFhaDgxQkFzeXE4ckhpSFpoNS9FMkNkNjBCRmhycWpWZWZiY09KdUFnVlo5dGsyCnV4eWZyWFhDZ2hZY1Q5cXpXaDQwSjVPTm9kWllTdkRzRUVEQXI0UXhiM0ZkVTUrbisva3NKNkQ4bUZxam5rN3gKMXpQdDFhODMxUTdLU1VXNWY0OTJxU1FVdVdDUUFyQ0E2M1pFQ3NycjNMQUlxWUJkUjJENmIyMXE1dWNDZ1lBWAowUjlpUUk3MFpsUzNzaytOelYzWWZMcGcwTTN0bDIvWEkrTTVjRkd4cjRrQVlpa0taNm5ZN2Rjc1NFV2hOTG11CmQ5RHlLN2JvaWlZSTFvelpYdlg3SWVKVDRQbExQZlVtZlAzOVNhMHptd2dFVkZ6Zk5aZVEveWFZL3RzN0NKblUKMk82Yzl2RGVSNU4zWFJ4N2tkaytoS0h6VjQzdlNOalZoRGZYdklqRm93S0JnUUNCMjZVSG4wNUJPL3F1SVFlNQpqazR2SHZMTFU1dzUrMXlmODlsTklpT0pIWUNEOHRINlp0ekF1ampzRUlPN3lvWWljVWt4SmtYVkNFeno4VlVHCk5ZVTQwaTl2ZkZkYURrdmN1eXQzNVg3aU9IK0FRQmc2QXQxaDBMS0NncktSTTRDU21ENHArK054YTNNbWJzWEoKNlhLNEN1bDlWeEpQeWNHcHdDS1pQdGwwR1E9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
      SECRET_KEY_BASE: "ca49e8c040430c7c3347f97eb5dee899eb90760811aa040c4037d0ca6ca3a4165e2e8d2a1b908fa858cfb7bafb477bfd8250c076a899f0f9c079d599747ce6b9"

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: forms_runner_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  bundle_cache:
  postgres_data:
  redis_data:
